server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_calend
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
     ddl-auto: update

#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 418729143839-ld6lv70d60a1huq9r63pvp06mirr1b9t.apps.googleusercontent.com
#            client-secret: iOeSXT9tiNJnLTRrVGX2704v