CREATE SCHEMA IF NOT EXISTS todo_schema;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE USER todo_service WITH PASSWORD 'calendar';
GRANT CONNECT ON DATABASE public TO todo_service;

GRANT USAGE ON SCHEMA todo_schema TO todo_service;
GRANT CREATE ON SCHEMA todo_schema TO todo_service;

ALTER DEFAULT PRIVILEGES IN SCHEMA todo_schema GRANT SELECT ON TABLES TO todo_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA todo_schema GRANT INSERT ON TABLES TO todo_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA todo_schema GRANT UPDATE ON TABLES TO todo_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA todo_schema GRANT SELECT ON SEQUENCES TO todo_service;