create table task (
    id int8 not null generated by default as identity,
    exec_period date,
    file_name varchar(255),
    full_desc varchar(1000),
    short_desc varchar(100),
    user_id int8 not null,
    primary key (id)
                  );
create table users (
    user_id int8 not null generated by default as identity,
    activation_code varchar(255),
    email varchar(255) not null ,
    enabled boolean not null,
    first_name varchar(255) not null ,
    last_name varchar(255) not null ,
    password varchar(60) not null ,
    role varchar(255),
    primary key (user_id));

alter table if exists task
    add constraint task_user_fk foreign key (user_id) references users